# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import inicio.managers


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', inicio.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
