# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20170807_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='dia_creado')),
                ('puesto', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'Personal',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.EmailField(default=None, max_length=254, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='personal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inicio.Personal'),
            preserve_default=False,
        ),
    ]
