# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 23:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_auto_20170807_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='personal',
        ),
        migrations.AddField(
            model_name='personal',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
            preserve_default=False,
        ),
    ]
