# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_auto_20170808_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='administrador'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_personal',
            field=models.BooleanField(default=False, verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff'),
        ),
    ]
